export const REGISTER_ACCOUNT = "REGISTER_ACCOUNT";
export const LOGIN = "LOGIN";
export const RECEIVE_TOKEN = "RECEIVE_TOKEN";
export const START_AUTH_REQUEST = "START_AUTH_REQUEST";
export const END_AUTH_REQUEST = "END_AUTH_REQUEST";

export const REQUEST_CONVERSATION = "REQUEST_CONVERSATION";
export const START_FETCH_CONVERSATION = "START_FETCH_CONVERSATION";
export const END_FETCH_CONVERSATION = "END_FETCH_CONVERSATION";
export const RECEIVE_CONVERSATION = "RECEIVE_CONVERSATION";
export const CHANGE_CONVERSATION = "CHANGE_CONVERSATION";

export const REQUEST_MESSAGE = "REQUEST_MESSAGE";
export const RECEIVE_MESSAGE = "RECEIVE_MESSAGE";
